In [4]:
import numpy as np


In [9]:
arr1 = np.array([1 , 2 , 5, 6, 7, 5])
print(f"array ={arr1} \ndata typr = { arr1.dtype } \ndimention = { arr1.shape} ")

array =[1 2 5 6 7 5] 
data typr = int64 
dimention = (6,) 


In [41]:
arr1_1 = np.array([[2,3,4] , [3,4,6] , [4,5,6]])
print(f"array ={arr1_1} \ndata typr = { arr1_1.dtype } \ndimention = { arr1_1.shape} ")

array =[[2 3 4]
 [3 4 6]
 [4 5 6]] 
data typr = int64 
dimention = (3, 3) 


In [6]:
arr2 = np.zeros((2,3))
print(f"array ={arr2}  \ndimention = { arr2.shape} ")

array =[[0. 0. 0.]
 [0. 0. 0.]]  
dimention = (2, 3) 


In [ ]:
prefill with one

In [18]:
arr3 = np.ones((6,5))
print(f"array ={arr3} \ndata typr = { arr3.dtype } \ndimention = { arr3.shape} ")

array =[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
data typr = float64 
dimention = (6, 5) 


In [21]:
arr4 = np.full((5,5) , 5)
print(f"array ={arr4} \ndata typr = { arr4.dtype } \ndimention = { arr4.shape} ")

array =[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] 
data typr = int64 
dimention = (5, 5) 


In [24]:
arr5 = np.eye(5)
print(f"array ={arr5} \ndata typr = { arr5.dtype } \ndimention = { arr5.shape} ")

array =[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
data typr = float64 
dimention = (5, 5) 


In [28]:
arr6 = np.arange(1,11)
print(f"array ={arr6} \ndata typr = { arr6.dtype } \ndimention = { arr6.shape} ")

array =[ 1  2  3  4  5  6  7  8  9 10] 
data typr = int64 
dimention = (10,) 


In [36]:
arr7 = np.linspace(0,100,4)
print(f"array ={arr7} \ndata typr = { arr7.dtype } \ndimention = { arr7.shape} ")

array =[  0.          33.33333333  66.66666667 100.        ] 
data typr = float64 
dimention = (4,) 


In [9]:
arr8 = np.array([[2,7,9] , [5,6,7] , [8,9,2]])
print(arr8.shape)
print(arr8.dtype)
print(arr8.size)
float_array = arr8.astype(np.float64)
print(arr8)

(3, 3)
int64
9
[[2 7 9]
 [5 6 7]
 [8 9 2]]
