In [37]:
import numpy as np

In [10]:
arr1 = np.array([[1,3,4],[6,7,8]])

print(arr1.reshape(3,2))
print(arr1.flatten())

[[1 3]
 [4 6]
 [7 8]]
[1 3 4 6 7 8]


In [14]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2[3])

4


In [22]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3[1,0])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


In [24]:
#1-d array
idx = [0,4,5]
print(arr2[idx])

[1 5 6]


In [27]:
arr4 = np.array([1 + 3j])
arr5 = np.array([1 + 4J])
print(arr4 + arr5, arr4.dtype)

[2.+7.j] complex128


In [39]:
arr6 = np.array([34,56,78,89])
t = arr6[3:5].copy
pt

<built-in method copy of numpy.ndarray object at 0x00000173E49B3270>
