In [1]:
import numpy as np

In [10]:
arr1 = np.array([[1,3,4],[6,7,8]])

print(arr1.reshape(3,2))
print(arr1.flatten())

[[1 3]
 [4 6]
 [7 8]]
[1 3 4 6 7 8]


In [14]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2[3])

4


In [22]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3[1,0])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


In [24]:
#1-d array
idx = [0,4,5]
print(arr2[idx])

[1 5 6]


In [27]:
arr4 = np.array([1 + 3j])
arr5 = np.array([1 + 4J])
print(arr4 + arr5, arr4.dtype)

[2.+7.j] complex128


In [39]:
arr6 = np.array([34,56,78,89])
t = arr6[3:5].copy
pt

<built-in method copy of numpy.ndarray object at 0x00000173E49B3270>


In [26]:
arr7 = np.array([[[4,6,7] , [5 , 8 ,9]] , [[5,9,0], [7,9,5]] ,[[3,7,0],[6,8,2]]])
print(arr7 , arr7.shape)
print(arr7[2,1,2])
print(arr7[:,:,0:])

[[[4 6 7]
  [5 8 9]]

 [[5 9 0]
  [7 9 5]]

 [[3 7 0]
  [6 8 2]]] (3, 2, 3)
2
[[[4 6 7]
  [5 8 9]]

 [[5 9 0]
  [7 9 5]]

 [[3 7 0]
  [6 8 2]]]


In [2]:
arr8 = np.array([2,4,6,8,9])
sq_arr8 = np.array(arr8 ** 2)
print(sq_arr8)

[ 4 16 36 64 81]


In [3]:
arr_1 = np.array([2,4])
arr_2 = np.array([[4,5],[9,8]])
print(arr_1 + arr_2)

[[ 6  9]
 [11 12]]


In [21]:
arr_vec = np.array([[3,5] , [4,7]])
print(np.sum(arr_vec))
mean = np.mean(arr_vec)
dev = np.std(arr_vec)
std_normalization = (arr_vec - mean)//dev
print(std_normalization)
print(np.pow(arr_vec , 5))
print(np.log10(arr_vec))
print(np.sqrt(arr_vec))
print(np.square(arr_vec))
print(np.min(arr_vec))
print(np.argmin(arr_vec))
print(np.argmax(arr_vec))
print(np.unique(arr_vec))
arr_u = np.array([2,3,2,4,7,7,4])
print(np.unique(arr_u))

19
[[-2.  0.]
 [-1.  1.]]
[[  243  3125]
 [ 1024 16807]]
[[0.47712125 0.69897   ]
 [0.60205999 0.84509804]]
[[1.73205081 2.23606798]
 [2.         2.64575131]]
[[ 9 25]
 [16 49]]
3
0
3
[3 4 5 7]
[2 3 4 7]
